<?php include("jwbfunctions.php");      counter('maincount'); ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head><link rel="shortcut icon" href="../Pics/camera2.ico" type="image/x-icon"><title>Visionary Solutions Group</title><meta http-equiv="Content-Type" content="text/html; charset=windows-1252"><meta name="author" content="James" ><meta name="Keywords" content="Visionary Solutions Group"><meta name="distribution" content="GLOBAL"><meta name="copyright" content="Copyright 2011 Visionary Solutions Group"><meta name="Description" content="Visionary Solutions Group Photos"><?php add2page('header.html'); ?><link rel="stylesheet" type="text/css" href="../Script/ddsmoothmenu.css" /><link rel="stylesheet" type="text/css" href="../Script/ddsmoothmenu-v.css" /><script type="text/javascript" src="../Script/jquery.min.js"></script><script type="text/javascript" src="../Script/ddsmoothmenu.js">/************************************************ Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)* This notice MUST stay intact for legal use* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code***********************************************/</script><script type="text/javascript">ddsmoothmenu.init({	mainmenuid: "smoothmenu1", //menu DIV id	orientation: "h", //Horizontal or vertical menu: Set to "h" or "v"	classname: "ddsmoothmenu", //class added to menu's outer DIV	//customtheme: ["#1c5a80", "#18374a"],	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]})</script></head><body>	<div id="page-background"><img src="../Pics/KC-Silhouette.jpg" width="100%" height="100%" alt="KC-Silhouette"></div>	<div id="content"><?php 	
$rootPath =  '../';	$photoPath =  '../photos';
$thumpPath =  '../thumbs';	$numDirs = 0;	listDirs($photoPath, $numDirs);sort($Tree);$directories = count($Tree);echo '<div id="smoothmenu1" class="ddsmoothmenu">'."\n";echo '<ul>'."\n";;echo '<li><a href="Main.php">Home</a></li>'."\n";$level = '';$switcher = 'OFF';$countMenu = 0;for ($j = 0; $j <= $directories-1; $j++) {	$Tree2[$j] = explode("/", $Tree[$j]);} for ($s = 0; $s <= $directories-1; $s++) {	$column = substr_count($Tree[$s], '/', 1);	$path = $Tree[$s];		$jpgCount = countImages($path);		if ($Tree2[$s][2] !== $Tree2[$s -1][2])	{			echo "\t<li><a href=\"#\">".$Tree2[$s][2]."</a>\n\t<ul>\n";	}	if (($Tree2[$s][2] == $Tree2[$s -1][2]) && ($Tree2[$s][3] !== $Tree2[$s -1][3]))	{			echo "\t\t<li><a href=\"#\">".$Tree2[$s][3]."</a>\n\t\t<ul>\n";	}		
	if ($jpgCount !== 0)
	{		$imagePath = str_replace('-n-', '&#38;', $Tree2[$s][$column]);		echo "\t\t\t<li><a href=\"pictures.php?path=".$path."\">".$imagePath.'&nbsp;&nbsp;('.$jpgCount.')</a></li>'."\n";
		//http://bw.visionarysolutionsgroup.com/photos/joseph/Disney%20Photpass%20J-n-S/DisneyPhotos004/30468140153.jpg
			}
	if (($Tree2[$s][2] == $Tree2[$s -1][2]) && ($Tree2[$s][3] !== $Tree2[$s +1][3]))	{			echo "\t\t\t</ul>\n\t\t</li>\n";	}				if ($Tree2[$s][2] !== $Tree2[$s +1][2])	{			echo "\t</ul>\n</li>\n";	}		if ($s == $directories-1)	{		echo "\n\t</ul>\n</li>\n";	}	}echo '</ul>';echo '<br style="clear: left" /></div>';?><!--<center><font face="Georgia" color="#2000FF"> 
<hr/><br/><br/><br<br/><h1>Count Down to Spring Fishing 2012</h1><h2>
<script type="text/javascript">//######################################################################################// Author: ricocheting.com// Version: v2.0// Date: 2011-03-31// Description: displays the amount of time until the "dateFuture" entered below.// NOTE: the month entered must be one less than current month. ie; 0=January, 11=December// NOTE: the hour is in 24 hour format. 0=12am, 15=3pm etc// format: dateFuture1 = new Date(year,month-1,day,hour,min,sec)// example: dateFuture1 = new Date(2003,03,26,14,15,00) = April 26, 2003 - 2:15:00 pmdateFuture1 = new Date(2012,03,28,8,0,0);
//Apr 30 - May 4 dates// TESTING: comment out the line below to print out the "dateFuture" for testing purposes//document.write(dateFuture +"<br />");//###################################//nothing beyond this pointfunction GetCount(ddate,iid){	dateNow = new Date();	//grab current date	amount = ddate.getTime() - dateNow.getTime();	//calc milliseconds between dates	delete dateNow;	// if time is already past	if(amount < 0){		document.getElementById(iid).innerHTML="Now!";	}	// else date is still good	else{		days=0;hours=0;mins=0;out="";

	amount = Math.floor(amount/1000);//kill the "milliseconds" so just secs		days=Math.floor(amount/86400);//days		amount=amount%86400;		hours=Math.floor(amount/3600);//hours		amount=amount%3600;		mins=Math.floor(amount/60);//minutes		amount=amount%60;		if(days != 0){out += days +" "+((days==1)?"day":"days")+", ";}		if(hours != 0){out += hours +" "+((hours==1)?"hour":"hours")+", ";}		out += mins +" "+((mins==1)?"min":"mins")+", ";		out = out.substr(0,out.length-2);		document.getElementById(iid).innerHTML=out;		setTimeout(function(){GetCount(ddate,iid)}, 1000);	}}window.onload=function(){	GetCount(dateFuture1, 'countbox1');	//you can add additional countdowns here (just make sure you create dateFuture2 and countbox2 etc for each)};</script><div id="countbox1"></div> <br/><br/><br/><br/><br/><br/>	<br/><br/><br/><br/>	</center>--><b><?php //add2page('footer.html');      add2page('copyright.html');      counteroutput('maincount.txt');?></b></font></div></body></html>