<?php

ini_set("error_log", "../logs/BeerErrors.log");
require './feedsClass.php';

$debugger     =  ((!isset($_GET['debug']))  ? ''    : htmlspecialchars($_GET['debug']));
$feedDays     =  30;
$key_words    =  array(
                       ' ale ', 
                       ' ales ', 
                       ' altbier ', 
                       ' bar ', 
                       ' barley', 
                       ' barleywine ', 
                       ' barrel', 
                       ' bars ', 
                       ' beer', 
                       ' berliner ', 
                       ' bier', 
                       ' bitter ', 
                       ' bière', 
                       ' bock ', 
                       ' bock ', 
                       ' booz', 
                       ' bottl',
                       ' bourbon', 
                       ' brew', 
                       ' bud ', 
                       ' cask', 
                       ' cellar', 
                       ' cider', 
                       ' distill', 
                       ' doppelbock ', 
                       ' dortmunder ', 
                       ' dunkel', 
                       ' festbier ', 
                       ' gin ', 
                       ' gins ', 
                       ' gose ', 
                       ' hefeweizen ', 
                       ' helles ', 
                       ' hop ', 
                       ' hopp ', 
                       ' hopps ', 
                       ' hops ', 
                       ' ipa', 
                       ' keg', 
                       ' kolsch', 
                       ' kölsch', 
                       ' lager', 
                       ' lambic ', 
                       ' maibock ', 
                       ' malt', 
                       ' market', 
                       ' mead', 
                       ' märzen ', 
                       ' pils ', 
                       ' pilsner', 
                       ' porter ', 
                       ' pub ', 
                       ' rum ', 
                       ' rums ', 
                       ' saison ', 
                       ' schwarzbier ', 
                       ' seltzer', 
                       ' spirits ', 
                       ' stout', 
                       ' tap', 
                       ' weissbier ', 
                       ' weizenbock ', 
                       ' whiskey', 
                       ' wine', 
                       ' witbier ', 
                       ' wort', 
                       ' yeast',
                       '6 pack', 
                       '6-er', 
                       '6-pack', 
                       '6er', 
                       'Octoberfest', 
                       'Oktoberfest'
                       );
$start        =  new beerFeedClass("", $debugger);

$start->filterFeedArticles($key_words); 

?>
